% % 

% clear all
% close all
% clc


save_name = 'Rocket_profiles';



trial_sw = 0; % Just for plotting
axis_sw = 1;  % axis equal and padding sw
front_view_sw = 1;
if trial_sw == 1
    scale_geom_major = 1;
    % close all
end

scale_map = [0.085 0.085 0.085];     % 0 to 1 profile will be multiplied with this
% CST WEIGHTS
% For LOWER, CST_wl_map will be multiplied by -1
% CST PART
                                                                                        % aa
CST_wu_map = { [  1 1  ];
               [  1 1]
               [  1 1]};   % exhaust

CST_wl_map = { [  -1 -1 ];...
               [  -1 -1 ]
               [  -1 -1 ]};   % exhaust
% engine 


x_locs = [0.10, 0.95, 1.90];

x_trans_map   = [0, 0, 0];
y_trans_map   = [0, 0, 0];
z_trans_map   = [0, 0, 0];
z_rot_deg_map = [0, 0, 0];  % To rotate the CST profile around local z axis

rot_map_global_deg = [0 0 0; 0 0 0; 0 0 0]  ;% To rotate the final profile around global body axis

dz_finite_TE_map = [0, 0, 0];

y_sta_map = x_locs;

plot_ind = [1:3];

 
for id_ind = [plot_ind]
    
    N = 200;    % Node num
    ID_profile = id_ind;
    wu_map  = CST_wu_map{ID_profile,:};
    wl_map  = CST_wl_map{ID_profile,:}; 
    
    
    %     fig=figure;set(fig,'units','normalized','outerposition',[0.2 0.2 0.6 0.6])
    %     ha = tight_subplot(1,1,[.1 .1],[0.1 0.1],[0.06  0.0200]);
    
            
        wu = wu_map;
        wl = wl_map;
    
    scaler = scale_map(ID_profile);
    x_trans = x_trans_map(ID_profile);
    dz = dz_finite_TE_map(ID_profile)/2;
    
    
%     [coord,x,xu,yu,xl,yl] = CST_airfoil(wl,wu,dz,N);
    [coord,x,xu,yu,xl,yl] = CST_airfoil_circle(wl,wu,dz,N);    
    
    % plot(coord(:,1),coord(:,2),'r-');hold on 
    
    
    % % xu    = xu * scaler;
    % % yu    = yu * scaler;
    % % xl    = xl * scaler;
    % % yl    = yl * scaler;

    coord = unique(coord,'rows','stable');
    coord_center = mean(coord);
    first_ind = find(all(coord == 0,2) == 1);
    coord = circshift(coord,first_ind-1);    

    coord = (coord-coord_center) * scaler + coord_center;


   

    x_var = x_locs(id_ind)*ones(size(coord,1),1);
    y_var = coord(:,1) - mean(coord(:,1)) ;
    z_var = coord(:,2);
    profile = [x_var,y_var,z_var];



    % Rotation-Profile z axis for node rotation
    [profile_rot] = z_rot_3d([profile(:,2),profile(:,3),profile(:,1)],1,z_rot_deg_map(id_ind));
    profile = [profile(:,1),profile_rot(:,1:2)];

    profile = profile + [x_trans_map(id_ind),y_trans_map(id_ind),z_trans_map(id_ind)];

    % Global z rotation
    center_rot = mean(profile);
    [profile_rot] = global_rotate([profile(:,1)-center_rot(1),profile(:,2)-center_rot(2),profile(:,3)-center_rot(3)],1,rot_map_global_deg(id_ind,:));
    profile = profile_rot + center_rot;

    % Translation
    profile = profile + [x_trans_map(id_ind),y_trans_map(id_ind),z_trans_map(id_ind)];




    
    % fig = figure;
    set(gcf,'units','normalized','outerposition',[0 0 1 1])


    plot3(profile(:,1),profile(:,2),profile(:,3),'k-');hold on   
    plot3(profile(1,1),profile(1,2),profile(1,3),'ro');hold on 

    len_profile_mid = floor(size(profile,1)/2);
    len_profile_mid_mid = floor(len_profile_mid/2);
    
    plot3(profile(end-len_profile_mid,1),profile(end-len_profile_mid,2),profile(end-len_profile_mid,3),'mo');hold on
    plot3(profile(len_profile_mid_mid,1),profile(len_profile_mid_mid,2),profile(len_profile_mid_mid,3),'co');hold on 
    
    plot3(profile(end,1),profile(end,2),profile(end,3),'go');hold on 
    
    % zlim([-1.1 -0.9])
        % zlim([-1.1 -0.6])

    % axis equal
    grid on
    %%
    
    
    
   eval(['profile_data.Profile_' num2str(id_ind) ' = profile;'])

    
    
end
    
    % xlim([-0.1,1.1]*scaler + x_trans)
    % ylim([-1,1.5]/4*3*scaler)
    xlabel('X')
    ylabel('Y')
    zlabel('Z')    
    % view(87,1)
        view(0,0)
    
    fgh = findobj('Type','figure');
    set(findall(fgh,'Type','axes'),'fontsize',12)    
    set(findall(fgh,'Type','axes'),'Linewidth',1.2)
    set(findall(fgh,'fontweight','normal'),'fontweight','bold')
    set(findall(fgh,'Type','line'),'Linewidth',2)

    if axis_sw == 1  % padding sw
        axis equal
        axis manual
        view([-55 20])

        if front_view_sw == 1
         view([-90 2])
        end
    end


% Save Part
save(save_name,'profile_data');










%% APPENDIX ---------------------------------------------------------------




% FUNCTIONS
function [coord,x,xu,yu,xl,yl] = CST_airfoil(wl,wu,dz,N)

% Description : Create a set of airfoil coordinates using CST parametrization method 
% Input  : wl = CST weight of lower surface
%          wu = CST weight of upper surface
%          dz = trailing edge thickness
% Output : coord = set of x-y coordinates of airfoil generated by CST


% Create x coordinate
x=ones(N+1,1);y=zeros(N+1,1);zeta=zeros(N+1,1);
for i=1:N+1
    zeta(i)=2*pi/N*(i-1);
    x(i)=0.5*(cos(zeta(i))+1);
end

% N1 and N2 parameters (N1 = 0.5 and N2 = 1 for airfoil shape)
N1 = 0.5;
N2 = 1;

zerind = find(x(:,1) == 0); % Used to separate upper and lower surfaces

xl= x(1:zerind-1); % Lower surface x-coordinates
xu = x(zerind:end); % Upper surface x-coordinates

[yl,S] = ClassShape(wl,xl,N1,N2,-dz); % Call ClassShape function to determine lower surface y-coordinates
% % % % figure
% % % % plot(1:50,S)
% % % % hold on
[yu,S] = ClassShape(wu,xu,N1,N2,dz);  % Call ClassShape function to determine upper surface y-coordinates
% % % plot(1:51,S)
y = [yl;yu]; % Combine upper and lower y coordinates

coord = [x y]; % Combine x and y into single output

end


function [coord,x,xu,yu,xl,yl] = CST_airfoil_circle(wl,wu,dz,N)

% Description : Create a set of airfoil coordinates using CST parametrization method 
% Input  : wl = CST weight of lower surface
%          wu = CST weight of upper surface
%          dz = trailing edge thickness
% Output : coord = set of x-y coordinates of airfoil generated by CST


% Create x coordinate
x=ones(N+1,1);y=zeros(N+1,1);zeta=zeros(N+1,1);
for i=1:N+1
    zeta(i)=2*pi/N*(i-1);
    x(i)=0.5*(cos(zeta(i))+1);
end

% N1 and N2 parameters (N1 = 0.5 and N2 = 1 for airfoil shape)
N1 = 0.5;
N2 = 0.5;

zerind = find(x(:,1) == 0); % Used to separate upper and lower surfaces

xl= x(1:zerind-1); % Lower surface x-coordinates
xu = x(zerind:end); % Upper surface x-coordinates

[yl,S] = ClassShape(wl,xl,N1,N2,-dz); % Call ClassShape function to determine lower surface y-coordinates
% % % % figure
% % % % plot(1:50,S)
% % % % hold on
[yu,S] = ClassShape(wu,xu,N1,N2,dz);  % Call ClassShape function to determine upper surface y-coordinates
% % % plot(1:51,S)
y = [yl;yu]; % Combine upper and lower y coordinates

coord = [x y]; % Combine x and y into single output

end

%% Function to calculate class and shape function
% function [y] = ClassShape(w,x,N1,N2,dz);
function [y,S] = ClassShape(w,x,N1,N2,dz);


% Class function; taking input of N1 and N2
for i = 1:size(x,1)
    C(i,1) = x(i)^N1*((1-x(i))^N2);
end

% Shape function; using Bernstein Polynomials
n = size(w,2)-1; % Order of Bernstein polynomials

for i = 1:n+1
     K(i) = factorial(n)/(factorial(i-1)*(factorial((n)-(i-1))));
end

for i = 1:size(x,1)
    S(i,1) = 0;
    for j = 1:n+1
        S(i,1) = S(i,1) + w(j)*K(j)*x(i)^(j-1)*((1-x(i))^(n-(j-1)));

    end
end

% Calculate y output
for i = 1:size(x,1)
   y(i,1) = C(i,1)*S(i,1) + x(i)*dz;
end


end


function P_out = correct3DProfile(P, desired_order, n, start_index)
% correct3DProfile - Reorders a 3D closed profile based on normal and start node
%
% Inputs:
%   P             - Nx3 matrix of 3D coordinates (closed or open)
%   desired_order - 'ccw' or 'cw' (desired polygon orientation)
%   n             - 1x3 unit normal vector (e.g., [1 0 0])
%   start_index   - Index of the node you want as starting point (1-based)
%                   for input profile
%
% Output:
%   P_out         - (N+1)x3 matrix of reordered and closed profile


    % Rotate so start_index becomes the first
    P = [P(start_index:end, :); P(1:start_index-1, :)];



    % Ensure P is closed
    if any(P(1,:) ~= P(end,:))
        P = [P; P(1,:)];  % Close the loop
    end

    % Create 2D local basis perpendicular to the normal vector
    if all(n == [1 0 0])
        temp = [0 1 0];
    else
        temp = [1 0 0];
    end
    u = cross(n, temp); u = u / norm(u);
    v = cross(n, u);    v = v / norm(v);

    % Project to 2D using the local u-v plane
    proj2D = [(P * u'), (P * v')];
    x = proj2D(:,1);
    y = proj2D(:,2);

    % Compute signed area (shoelace formula)
    area = 0.5 * sum(x(1:end-1).*y(2:end) - x(2:end).*y(1:end-1));

    % Reverse order if it doesn't match desired orientation
    if (strcmpi(desired_order, 'ccw') && area < 0) || ...
       (strcmpi(desired_order, 'cw') && area > 0)
        P = flipud(P);
    end

    % Remove duplicate last point before rotating
    P = P(1:end-1, :);

    % Ensure start_index is valid
    N = size(P,1);
    if start_index < 1 || start_index > N
        error('start_index must be between 1 and %d', N);
    end


    % Close the loop
    P_out = [P; P(1,:)];
end



function [profile_rot] = z_rot_3d(profile_in,index_center,angle_deg)

% Z Rotation profile 1-----------------------------------------------------
R_matrix_z = [cosd(angle_deg), -sind(angle_deg) 0;sind(angle_deg),cosd(angle_deg) 0;0 0 1];
center = profile_in(index_center,:)';
rotated_points = R_matrix_z * (profile_in' - center);
rotated_points = rotated_points + center;

profile_rot = rotated_points';

% Z Rotation profile 1-----------------------------------------------------



end


function [profile_rot] = global_rotate(profile_in,index_center,angle_deg)

% Z Rotation profile 1-----------------------------------------------------
Rx = [1 0 0; 0 cosd(angle_deg(1)), -sind(angle_deg(1)); 0 sind(angle_deg(1)), cosd(angle_deg(1))];
Ry = [cosd(angle_deg(2)), 0,  -sind(angle_deg(2)); 0 1 0; sind(angle_deg(2)), 0, cosd(angle_deg(2)) ];
Rz = [cosd(angle_deg(3)), -sind(angle_deg(3)) 0;sind(angle_deg(3)),cosd(angle_deg(3)) 0;0 0 1];

center = profile_in(index_center,:)';
rotated_points = Rx*Ry*Rz * (profile_in' - center);
rotated_points = rotated_points + center;

profile_rot = rotated_points';

% Z Rotation profile 1-----------------------------------------------------



end





